"""Rebooting new db

Revision ID: 0639db1ccdf8
Revises: 
Create Date: 2018-06-27 15:11:35.661299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0639db1ccdf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=64), nullable=True),
    sa.Column('partner_uni', sa.String(length=128), nullable=True),
    sa.Column('partner_uni_module_1', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_module_1_title', sa.String(length=128), nullable=True),
    sa.Column('partner_uni_module_1_credits', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_module_2', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_module_2_title', sa.String(length=128), nullable=True),
    sa.Column('partner_uni_module_2_credits', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_country', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_state', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_continent', sa.String(length=64), nullable=True),
    sa.Column('partner_uni_image', sa.String(length=64), nullable=True),
    sa.Column('nus_module_1', sa.String(length=64), nullable=True),
    sa.Column('nus_module_1_title', sa.String(length=128), nullable=True),
    sa.Column('nus_module_1_credits', sa.String(length=64), nullable=True),
    sa.Column('nus_module_2', sa.String(length=64), nullable=True),
    sa.Column('nus_module_2_title', sa.String(length=128), nullable=True),
    sa.Column('nus_module_2_credits', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=True),
    sa.Column('module_title', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('module_description', sa.String(length=128), nullable=True),
    sa.Column('module_credit', sa.String(length=64), nullable=True),
    sa.Column('workload', sa.String(length=128), nullable=True),
    sa.Column('preclusion', sa.String(length=128), nullable=True),
    sa.Column('types', sa.String(length=128), nullable=True),
    sa.Column('history', sa.String(length=128), nullable=True),
    sa.Column('corequisite', sa.String(length=128), nullable=True),
    sa.Column('prerequisite', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('modules')
    op.drop_table('mapping')
    # ### end Alembic commands ###
