"""Add brochure pdf link

Revision ID: 0d08ce4d1066
Revises: 5cc74666279d
Create Date: 2018-07-02 02:10:54.926900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d08ce4d1066'
down_revision = '5cc74666279d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('brochure', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'brochure')
    # ### end Alembic commands ###
