"""empty message

Revision ID: 232d4cd0cbdd
Revises: f89a61f02a3f
Create Date: 2018-06-03 10:40:39.378545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232d4cd0cbdd'
down_revision = 'f89a61f02a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('faculty', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('nus_module_1', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('nus_module_1_title', sa.String(length=128), nullable=True))
    op.add_column('mapping', sa.Column('nus_module_2', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('nus_module_2_title', sa.String(length=128), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni', sa.String(length=128), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_module_1', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_module_1_credits', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_module_1_title', sa.String(length=128), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_module_2', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_module_2_credits', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_module_2_title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'partner_uni_module_2_title')
    op.drop_column('mapping', 'partner_uni_module_2_credits')
    op.drop_column('mapping', 'partner_uni_module_2')
    op.drop_column('mapping', 'partner_uni_module_1_title')
    op.drop_column('mapping', 'partner_uni_module_1_credits')
    op.drop_column('mapping', 'partner_uni_module_1')
    op.drop_column('mapping', 'partner_uni')
    op.drop_column('mapping', 'nus_module_2_title')
    op.drop_column('mapping', 'nus_module_2')
    op.drop_column('mapping', 'nus_module_1_title')
    op.drop_column('mapping', 'nus_module_1')
    op.drop_column('mapping', 'faculty')
    # ### end Alembic commands ###
