"""Added images for partner unis to mapping table

Revision ID: 23afcb6e3437
Revises: fd2b17761d77
Create Date: 2018-06-06 03:18:38.262779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23afcb6e3437'
down_revision = 'fd2b17761d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('partner_uni_image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'partner_uni_image')
    # ### end Alembic commands ###
