"""Adding cost into mapping table

Revision ID: 5cc74666279d
Revises: 0639db1ccdf8
Create Date: 2018-07-01 04:18:18.233382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc74666279d'
down_revision = '0639db1ccdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('cost_native_avg', sa.Integer(), nullable=True))
    op.add_column('mapping', sa.Column('cost_native_max', sa.Integer(), nullable=True))
    op.add_column('mapping', sa.Column('cost_native_min', sa.Integer(), nullable=True))
    op.add_column('mapping', sa.Column('cost_sgd_avg', sa.Integer(), nullable=True))
    op.add_column('mapping', sa.Column('cost_sgd_max', sa.Integer(), nullable=True))
    op.add_column('mapping', sa.Column('cost_sgd_min', sa.Integer(), nullable=True))
    op.add_column('mapping', sa.Column('currency_type', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('exchange_rate_to_sgd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'exchange_rate_to_sgd')
    op.drop_column('mapping', 'currency_type')
    op.drop_column('mapping', 'cost_sgd_min')
    op.drop_column('mapping', 'cost_sgd_max')
    op.drop_column('mapping', 'cost_sgd_avg')
    op.drop_column('mapping', 'cost_native_min')
    op.drop_column('mapping', 'cost_native_max')
    op.drop_column('mapping', 'cost_native_avg')
    # ### end Alembic commands ###
