"""empty message

Revision ID: 761f5fd6aa9f
Revises: 
Create Date: 2018-06-01 20:42:30.810515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761f5fd6aa9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=True),
    sa.Column('module_title', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('module_description', sa.String(length=128), nullable=True),
    sa.Column('module_credit', sa.String(length=64), nullable=True),
    sa.Column('workload', sa.String(length=128), nullable=True),
    sa.Column('preclusion', sa.String(length=128), nullable=True),
    sa.Column('types', sa.String(length=128), nullable=True),
    sa.Column('history', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    # ### end Alembic commands ###
