"""Fixed bug for nus_module_1_credits and nus_module_2_credits

Revision ID: 884f4cdd9227
Revises: 23afcb6e3437
Create Date: 2018-06-17 01:05:03.576438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884f4cdd9227'
down_revision = '23afcb6e3437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('nus_module_1_credits', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('nus_module_2_credits', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'nus_module_2_credits')
    op.drop_column('mapping', 'nus_module_1_credits')
    # ### end Alembic commands ###
