"""updated modules table

Revision ID: f89a61f02a3f
Revises: 7a5c3079348d
Create Date: 2018-06-01 22:29:24.613265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89a61f02a3f'
down_revision = '7a5c3079348d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('corequisite', sa.String(length=128), nullable=True))
    op.add_column('modules', sa.Column('prerequisite', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'prerequisite')
    op.drop_column('modules', 'corequisite')
    # ### end Alembic commands ###
