"""Added countries, states, continents to mapping table

Revision ID: fd2b17761d77
Revises: 232d4cd0cbdd
Create Date: 2018-06-06 00:48:07.200447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2b17761d77'
down_revision = '232d4cd0cbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping', sa.Column('partner_uni_continent', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_country', sa.String(length=64), nullable=True))
    op.add_column('mapping', sa.Column('partner_uni_state', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping', 'partner_uni_state')
    op.drop_column('mapping', 'partner_uni_country')
    op.drop_column('mapping', 'partner_uni_continent')
    # ### end Alembic commands ###
